spring.application.name=shelli-gateway
spring.cloud.config.enabled=false
logging.level.org.springframework.web=INFO
logging.level.org.springframework.context=INFO

# Groq LLM Configuration
groq.api.key=${GROQ_API_KEY}
groq.api.model=openai/gpt-oss-20b